project:
  type: website
  output-dir: docs
  title: "lumalazarini.github.io"
  
website:
  title: "Luma Lazarini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: Research.qmd
        text: Research
      - href: courses.qmd
        text: Courses
      - href: resume2.pdf
        text: Resume
        target: _blank
    page-footer: 
      background: dark
format:
  html:
    theme: style.scss
    mainfont: Lato
    fontcolor: $brown
    toc: true
    page-layout: full

editor: visual

